/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultTasksPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_TASKS = "vault-tasks-view";
var VIEW_TITLE = "Vault tasks";
var DEFERRED_UNTIL_KEY = "deffered-until";
var HIDDEN_FROM_TASKS_KEY = "hide-from-vault-tasks";
var FRONTMATTER_PATTERN = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/;
var TASK_LINE_PATTERN = /^(\s*(?:[-*+]|\d+[.)])\s+\[)(.)(\].*)$/;
var TASK_TEXT_PATTERN = /^\s*(?:[-*+]|\d+[.)])\s+\[.\]\s?(.*)$/;
var VaultTasksPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.autoRefreshPaused = false;
    this.filter = "pending";
    this.groups = [];
    this.lastError = null;
    this.manualRefreshRequired = false;
    this.queuedRefresh = false;
    this.refreshing = false;
    this.showConnections = false;
    this.scheduleRefresh = (0, import_obsidian.debounce)(() => {
      void this.refreshIndex();
    }, 250, true);
  }
  async onload() {
    this.registerView(VIEW_TYPE_TASKS, (leaf) => new VaultTasksView(leaf, this));
    this.addRibbonIcon("list-todo", "Open task list", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-task-list",
      name: "Open task list",
      callback: () => {
        void this.activateView();
      }
    });
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (this.isMarkdownFile(file)) {
          this.requestAutoRefresh();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (this.isMarkdownFile(file)) {
          this.requestAutoRefresh();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (this.isMarkdownFile(file)) {
          this.requestAutoRefresh();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file) => {
        if (this.isMarkdownFile(file)) {
          this.requestAutoRefresh();
        }
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        if (this.isMarkdownFile(file)) {
          this.requestAutoRefresh();
        }
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("deleted", (file) => {
        if (this.isMarkdownFile(file)) {
          this.requestAutoRefresh();
        }
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("resolve", (file) => {
        if (this.isMarkdownFile(file)) {
          this.requestAutoRefresh();
        }
      })
    );
    this.app.workspace.onLayoutReady(() => {
      void this.refreshIndex();
    });
  }
  getFilter() {
    return this.filter;
  }
  getSnapshot() {
    return {
      error: this.lastError,
      filter: this.filter,
      groups: this.groups,
      refreshing: this.refreshing,
      showConnections: this.showConnections
    };
  }
  getShowConnections() {
    return this.showConnections;
  }
  getReadableLineLengthEnabled() {
    var _a;
    const vaultWithConfig = this.app.vault;
    return Boolean((_a = vaultWithConfig.getConfig) == null ? void 0 : _a.call(vaultWithConfig, "readableLineLength"));
  }
  hasPendingManualRefresh() {
    return this.manualRefreshRequired;
  }
  async applyTaskChanges() {
    this.autoRefreshPaused = false;
    this.manualRefreshRequired = false;
    await this.updateHeaderControls();
    await this.refreshIndex();
  }
  async setFilter(filter) {
    if (this.filter === filter) {
      return;
    }
    this.filter = filter;
    await this.renderAllViews();
  }
  async setShowConnections(showConnections) {
    if (this.showConnections === showConnections) {
      return;
    }
    this.showConnections = showConnections;
    await this.updateHeaderControls();
    await this.renderAllViews();
  }
  async activateView() {
    let leaf = this.getMainTaskLeaf();
    if (!leaf) {
      leaf = this.app.workspace.getLeaf("tab");
      await leaf.setViewState({
        type: VIEW_TYPE_TASKS,
        active: true
      });
    }
    this.app.workspace.setActiveLeaf(leaf, { focus: true });
    await this.app.workspace.revealLeaf(leaf);
  }
  async openTask(task) {
    var _a;
    const leaf = this.getPreferredNoteLeaf();
    await leaf.openFile(task.file);
    this.app.workspace.setActiveLeaf(leaf, { focus: true });
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view || ((_a = view.file) == null ? void 0 : _a.path) !== task.file.path) {
      return;
    }
    const line = Math.min(task.line, view.editor.lastLine());
    view.editor.setCursor({ line, ch: 0 });
    view.editor.scrollIntoView(
      {
        from: { line, ch: 0 },
        to: { line, ch: 0 }
      },
      true
    );
    view.editor.focus();
  }
  async refreshIndex() {
    if (this.refreshing) {
      this.queuedRefresh = true;
      return;
    }
    this.refreshing = true;
    await this.renderAllViews();
    try {
      this.groups = await this.buildTaskGroups();
      this.lastError = null;
    } catch (error) {
      this.lastError = error instanceof Error ? error.message : "Could not refresh the task list.";
    } finally {
      this.refreshing = false;
      await this.renderAllViews();
    }
    if (this.queuedRefresh) {
      this.queuedRefresh = false;
      void this.refreshIndex();
    }
  }
  async toggleTask(task, completed) {
    var _a;
    try {
      this.autoRefreshPaused = true;
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (((_a = activeView == null ? void 0 : activeView.file) == null ? void 0 : _a.path) === task.file.path) {
        this.toggleTaskInEditor(activeView.editor, task, completed);
      } else {
        await this.app.vault.process(task.file, (content) => {
          return updateTaskInContent(content, task, completed);
        });
      }
      const nextLine = setTaskCompletion(task.rawLine, completed);
      if (nextLine !== null) {
        task.completed = completed;
        task.rawLine = nextLine;
        task.renderedLine = nextLine.trimStart();
      }
      this.manualRefreshRequired = true;
      await this.updateHeaderControls();
      return true;
    } catch (error) {
      const message = error instanceof Error ? error.message : "Could not update the task.";
      new import_obsidian.Notice(message);
      if (!this.manualRefreshRequired) {
        this.autoRefreshPaused = false;
      }
      await this.updateHeaderControls();
      return false;
    }
  }
  async setDeferredUntil(file, deferredUntil) {
    try {
      await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
        frontmatter[DEFERRED_UNTIL_KEY] = deferredUntil;
      });
      await this.refreshIndex();
    } catch (error) {
      const message = error instanceof Error ? error.message : "Could not update the defer-until date.";
      new import_obsidian.Notice(message);
    }
  }
  async hideFromTaskList(file) {
    try {
      await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
        frontmatter[HIDDEN_FROM_TASKS_KEY] = true;
      });
      await this.refreshIndex();
      new import_obsidian.Notice(
        `Hidden from vault tasks. Remove \`${HIDDEN_FROM_TASKS_KEY}: true\` to show it again.`
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : "Could not hide the note from the task list.";
      new import_obsidian.Notice(message);
    }
  }
  async setAllTasksCompletion(file, completed) {
    var _a;
    let updatedCount = 0;
    try {
      this.autoRefreshPaused = true;
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (((_a = activeView == null ? void 0 : activeView.file) == null ? void 0 : _a.path) === file.path) {
        updatedCount = updateAllTasksInEditor(activeView.editor, completed);
      } else {
        await this.app.vault.process(file, (content) => {
          const result = updateAllTasksInContent(content, completed);
          updatedCount = result.updatedCount;
          return result.content;
        });
      }
      this.autoRefreshPaused = false;
      this.manualRefreshRequired = false;
      await this.updateHeaderControls();
      if (updatedCount === 0) {
        new import_obsidian.Notice(completed ? "No open tasks to complete." : "No completed tasks to cancel.");
        return;
      }
      await this.refreshIndex();
    } catch (error) {
      this.autoRefreshPaused = false;
      const message = error instanceof Error ? error.message : "Could not update the tasks in this note.";
      new import_obsidian.Notice(message);
      await this.updateHeaderControls();
    }
  }
  async buildTaskGroups() {
    const taskFiles = this.app.vault.getMarkdownFiles().flatMap((file) => {
      const taskItems = getTaskListItems(this.app.metadataCache.getFileCache(file));
      if (taskItems.length === 0) {
        return [];
      }
      return [{ file, taskItems }];
    });
    const groups = await Promise.all(
      taskFiles.map(async ({ file, taskItems }) => {
        const content = await this.app.vault.cachedRead(file);
        const lines = content.split(/\r?\n/);
        const tasks = taskItems.map((taskItem) => buildTaskItem(file, taskItem, lines)).filter((task) => task !== null).sort((left, right) => left.line - right.line);
        return {
          deferredUntil: extractDeferredUntil(content),
          file,
          hiddenFromTaskList: extractHiddenFromTaskList(content),
          noteTitle: file.basename,
          tasks
        };
      })
    );
    return groups.filter((group) => group.tasks.length > 0 && !group.hiddenFromTaskList).sort((left, right) => left.noteTitle.localeCompare(right.noteTitle));
  }
  getMainTaskLeaf() {
    let taskLeaf = null;
    this.app.workspace.iterateRootLeaves((leaf) => {
      if (taskLeaf || leaf.view.getViewType() !== VIEW_TYPE_TASKS) {
        return;
      }
      taskLeaf = leaf;
    });
    return taskLeaf;
  }
  isMarkdownFile(file) {
    return file instanceof import_obsidian.TFile && file.extension === "md";
  }
  getBacklinkFiles(file) {
    var _a;
    const backlinks = /* @__PURE__ */ new Map();
    const resolvedLinks = this.app.metadataCache.resolvedLinks;
    for (const [sourcePath, links] of Object.entries(resolvedLinks)) {
      if (sourcePath === file.path || !links[file.path]) {
        continue;
      }
      const sourceFile = this.app.vault.getAbstractFileByPath(sourcePath);
      if (sourceFile instanceof import_obsidian.TFile && sourceFile.extension === "md" && !isHiddenFromTaskListFrontmatter((_a = this.app.metadataCache.getFileCache(sourceFile)) == null ? void 0 : _a.frontmatter)) {
        backlinks.set(sourceFile.path, sourceFile);
      }
    }
    return Array.from(backlinks.values()).sort(
      (left, right) => left.basename.localeCompare(right.basename) || left.path.localeCompare(right.path)
    );
  }
  getPreferredNoteLeaf() {
    const leaf = this.app.workspace.getMostRecentLeaf(this.app.workspace.rootSplit);
    if (leaf && leaf.view.getViewType() !== VIEW_TYPE_TASKS) {
      return leaf;
    }
    return this.app.workspace.getLeaf("tab");
  }
  async renderAllViews() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_TASKS);
    await Promise.all(
      leaves.map(async (leaf) => {
        if (leaf.view instanceof VaultTasksView) {
          await leaf.view.render();
        }
      })
    );
  }
  requestAutoRefresh() {
    if (this.autoRefreshPaused) {
      return;
    }
    this.scheduleRefresh();
  }
  async updateHeaderControls() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_TASKS);
    for (const leaf of leaves) {
      if (leaf.view instanceof VaultTasksView) {
        leaf.view.updateHeaderControls();
      }
    }
  }
  toggleTaskInEditor(editor, task, completed) {
    const lines = collectEditorLines(editor);
    const targetLine = findTaskLine(lines, task);
    if (targetLine === null) {
      throw new Error("The task moved before it could be updated. Refresh and try again.");
    }
    const nextLine = setTaskCompletion(lines[targetLine], completed);
    if (nextLine === null) {
      throw new Error("The source line is no longer a standard Markdown task.");
    }
    editor.setLine(targetLine, nextLine);
  }
};
var VaultTasksView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.archiveButtonEl = null;
    this.connectionsButtonEl = null;
    this.filterButtons = /* @__PURE__ */ new Map();
    this.headerFilterEl = null;
    this.markdownHostEl = null;
    this.renderComponent = null;
    this.renderedTasks = /* @__PURE__ */ new Map();
  }
  getViewType() {
    return VIEW_TYPE_TASKS;
  }
  getDisplayText() {
    return VIEW_TITLE;
  }
  getIcon() {
    return "list-todo";
  }
  async onOpen() {
    this.contentEl.addClasses(["vault-tasks-view", "markdown-reading-view"]);
    this.ensureHeaderFilters();
    this.registerDomEvent(this.contentEl, "change", (event) => {
      const target = event.target;
      if (!(target instanceof HTMLInputElement) || target.type !== "checkbox") {
        return;
      }
      const key = target.dataset.taskKey;
      if (!key) {
        return;
      }
      const task = this.renderedTasks.get(key);
      if (!task) {
        return;
      }
      const nextChecked = target.checked;
      target.disabled = true;
      void (async () => {
        const didUpdate = await this.plugin.toggleTask(task, nextChecked);
        if (!didUpdate) {
          target.checked = !nextChecked;
        }
        target.disabled = false;
        this.updateHeaderControls();
      })();
    });
    this.registerDomEvent(this.contentEl, "click", (event) => {
      const target = event.target;
      if (!(target instanceof HTMLElement)) {
        return;
      }
      const linkEl = target.closest("a.internal-link");
      if (!linkEl) {
        return;
      }
      const linktext = linkEl.getAttribute("data-href");
      if (!linktext) {
        return;
      }
      event.preventDefault();
      event.stopPropagation();
      void this.app.workspace.openLinkText(linktext, "/", import_obsidian.Keymap.isModEvent(event));
    });
    await this.render();
  }
  async onClose() {
    var _a, _b;
    this.archiveButtonEl = null;
    this.connectionsButtonEl = null;
    (_a = this.headerFilterEl) == null ? void 0 : _a.remove();
    this.headerFilterEl = null;
    this.filterButtons.clear();
    this.markdownHostEl = null;
    this.renderedTasks.clear();
    (_b = this.renderComponent) == null ? void 0 : _b.unload();
    this.renderComponent = null;
    this.contentEl.empty();
  }
  async render() {
    var _a;
    const snapshot = this.plugin.getSnapshot();
    const { markdown, renderedGroups, renderedTasks } = buildRenderedDocument(
      snapshot,
      this.app.metadataCache,
      (file) => this.plugin.getBacklinkFiles(file)
    );
    this.ensureHeaderFilters();
    this.updateFilterButtons(snapshot.filter);
    (_a = this.renderComponent) == null ? void 0 : _a.unload();
    this.renderComponent = new import_obsidian.Component();
    this.addChild(this.renderComponent);
    this.renderedTasks.clear();
    this.contentEl.empty();
    this.contentEl.addClasses(["vault-tasks-view", "markdown-reading-view"]);
    this.contentEl.toggleClass(
      "is-readable-line-width",
      this.plugin.getReadableLineLengthEnabled()
    );
    this.markdownHostEl = this.contentEl.createDiv({
      cls: [
        "vault-tasks-view__document",
        "markdown-preview-view",
        "markdown-rendered"
      ]
    });
    this.markdownHostEl.toggleClass(
      "is-readable-line-width",
      this.plugin.getReadableLineLengthEnabled()
    );
    const sizerEl = this.markdownHostEl.createDiv({
      cls: ["markdown-preview-sizer", "vault-tasks-view__sizer"]
    });
    await import_obsidian.MarkdownRenderer.render(this.app, markdown, sizerEl, "/", this.renderComponent);
    const checkboxes = Array.from(sizerEl.querySelectorAll("input[type='checkbox']"));
    for (const [index, checkbox] of checkboxes.entries()) {
      const task = renderedTasks[index];
      if (!task) {
        continue;
      }
      checkbox.dataset.taskKey = task.key;
      this.renderedTasks.set(task.key, task);
      this.addJumpButton(checkbox, task);
    }
    const headings = Array.from(sizerEl.querySelectorAll("h2"));
    for (const [index, headingEl] of headings.entries()) {
      const group = renderedGroups[index];
      if (!group) {
        continue;
      }
      this.bindHeadingMenu(headingEl, group);
      this.decorateHeadingContext(headingEl);
    }
  }
  updateHeaderControls() {
    this.ensureHeaderFilters();
    this.updateArchiveButton();
    this.updateConnectionsButton();
    this.updateFilterButtons(this.plugin.getFilter());
  }
  ensureHeaderFilters() {
    var _a, _b, _c;
    if ((_a = this.headerFilterEl) == null ? void 0 : _a.isConnected) {
      return;
    }
    const actionsEl = (_c = this.containerEl.querySelector(".view-actions")) != null ? _c : (_b = this.containerEl.closest(".workspace-leaf-content")) == null ? void 0 : _b.querySelector(".view-actions");
    if (!actionsEl) {
      return;
    }
    const filterEl = createDiv({ cls: "vault-tasks-view__header-filters" });
    for (const filter of ["all", "pending", "completed"]) {
      const buttonEl = filterEl.createEl("button", {
        cls: ["clickable-icon", "view-action", "vault-tasks-view__header-filter"],
        attr: {
          "data-tooltip-position": "bottom",
          "aria-label": `Show ${filterLabel(filter)} tasks`,
          title: `Show ${filterLabel(filter)} tasks`,
          type: "button"
        }
      });
      (0, import_obsidian.setIcon)(buttonEl, filterIcon(filter));
      this.registerDomEvent(buttonEl, "click", () => {
        void this.plugin.setFilter(filter);
      });
      this.filterButtons.set(filter, buttonEl);
    }
    const archiveButtonEl = filterEl.createEl("button", {
      cls: ["clickable-icon", "view-action", "vault-tasks-view__header-filter"],
      attr: {
        "data-tooltip-position": "bottom",
        "aria-label": "Refresh task list",
        title: "Refresh task list",
        type: "button"
      }
    });
    (0, import_obsidian.setIcon)(archiveButtonEl, "archive");
    this.registerDomEvent(archiveButtonEl, "click", () => {
      void this.plugin.applyTaskChanges();
    });
    this.archiveButtonEl = archiveButtonEl;
    const connectionsButtonEl = filterEl.createEl("button", {
      cls: ["clickable-icon", "view-action", "vault-tasks-view__header-filter"],
      attr: {
        "data-tooltip-position": "bottom",
        "aria-label": "Toggle connections context",
        title: "Toggle connections context",
        type: "button"
      }
    });
    (0, import_obsidian.setIcon)(connectionsButtonEl, "waypoints");
    this.registerDomEvent(connectionsButtonEl, "click", () => {
      void this.plugin.setShowConnections(!this.plugin.getShowConnections());
    });
    this.connectionsButtonEl = connectionsButtonEl;
    const anchorEl = actionsEl.lastElementChild;
    if (anchorEl) {
      actionsEl.insertBefore(filterEl, anchorEl);
    } else {
      actionsEl.appendChild(filterEl);
    }
    this.headerFilterEl = filterEl;
    this.updateHeaderControls();
  }
  updateFilterButtons(activeFilter) {
    for (const [filter, buttonEl] of this.filterButtons.entries()) {
      buttonEl.toggleClass("is-active", filter === activeFilter);
      buttonEl.setAttr("aria-pressed", filter === activeFilter ? "true" : "false");
    }
  }
  updateArchiveButton() {
    if (!this.archiveButtonEl) {
      return;
    }
    const hasPendingRefresh = this.plugin.hasPendingManualRefresh();
    this.archiveButtonEl.toggleClass("is-active", hasPendingRefresh);
    this.archiveButtonEl.setAttr("aria-pressed", hasPendingRefresh ? "true" : "false");
  }
  updateConnectionsButton() {
    if (!this.connectionsButtonEl) {
      return;
    }
    const showConnections = this.plugin.getShowConnections();
    this.connectionsButtonEl.toggleClass("is-active", showConnections);
    this.connectionsButtonEl.setAttr("aria-pressed", showConnections ? "true" : "false");
  }
  addJumpButton(checkboxEl, task) {
    const listItemEl = checkboxEl.closest("li");
    if (!listItemEl) {
      return;
    }
    const jumpButtonEl = createEl("span", {
      cls: "vault-tasks-view__task-jump",
      text: "\u2197",
      attr: {
        "aria-label": `Open task source in ${task.file.basename}`,
        "data-tooltip-position": "bottom",
        role: "button",
        tabindex: "0",
        title: `Open ${task.file.basename} at line ${task.line + 1}`
      }
    });
    this.registerDomEvent(jumpButtonEl, "click", (event) => {
      event.preventDefault();
      event.stopPropagation();
      void this.plugin.openTask(task);
    });
    this.registerDomEvent(jumpButtonEl, "keydown", (event) => {
      if (event.key !== "Enter" && event.key !== " ") {
        return;
      }
      event.preventDefault();
      event.stopPropagation();
      void this.plugin.openTask(task);
    });
    listItemEl.appendChild(jumpButtonEl);
  }
  bindHeadingMenu(headingEl, group) {
    const titleLinkEl = headingEl.querySelector("a.internal-link");
    if (!titleLinkEl) {
      return;
    }
    this.registerDomEvent(titleLinkEl, "contextmenu", (event) => {
      event.preventDefault();
      event.stopPropagation();
      const menu = new import_obsidian.Menu();
      menu.addItem((item) => {
        item.setTitle("Defer until").setIcon("calendar-days").onClick(() => {
          new DeferUntilModal(
            this.app,
            group.noteTitle,
            group.deferredUntil,
            async (deferredUntil) => {
              await this.plugin.setDeferredUntil(group.file, deferredUntil);
            }
          ).open();
        });
      });
      menu.addItem((item) => {
        item.setTitle("Complete all").setIcon("check").onClick(() => {
          void this.plugin.setAllTasksCompletion(group.file, true);
        });
      });
      menu.addItem((item) => {
        item.setTitle("Cancel all").setIcon("circle").onClick(() => {
          void this.plugin.setAllTasksCompletion(group.file, false);
        });
      });
      menu.addItem((item) => {
        item.setTitle("Hide").setIcon("eye-off").onClick(() => {
          void this.plugin.hideFromTaskList(group.file);
        });
      });
      menu.showAtMouseEvent(event);
    });
  }
  decorateHeadingContext(headingEl) {
    var _a, _b, _c;
    const headingBlockEl = (_a = headingEl.closest(".el-h2")) != null ? _a : headingEl;
    let nextBlockEl = headingBlockEl.nextElementSibling;
    while (nextBlockEl) {
      const paragraphEl = nextBlockEl instanceof HTMLParagraphElement ? nextBlockEl : nextBlockEl.querySelector(":scope > p");
      if (!(paragraphEl instanceof HTMLParagraphElement)) {
        return;
      }
      const text = (_c = (_b = paragraphEl.textContent) == null ? void 0 : _b.trim()) != null ? _c : "";
      if (text.startsWith("Deferred until:")) {
        paragraphEl.addClass("vault-tasks-view__deferred");
        nextBlockEl = nextBlockEl.nextElementSibling;
        continue;
      }
      if (text.startsWith("Related to:")) {
        paragraphEl.addClass("vault-tasks-view__connections");
        const linkEls = Array.from(
          paragraphEl.querySelectorAll("a.internal-link")
        );
        for (const linkEl of linkEls) {
          linkEl.addClass("vault-tasks-view__connections-link");
        }
        nextBlockEl = nextBlockEl.nextElementSibling;
        continue;
      }
      return;
    }
  }
};
var DeferUntilModal = class extends import_obsidian.Modal {
  constructor(app, noteTitle, currentDeferredUntil, onSubmitDate) {
    super(app);
    this.noteTitle = noteTitle;
    this.currentDeferredUntil = currentDeferredUntil;
    this.onSubmitDate = onSubmitDate;
    this.dateInputEl = null;
    this.minimumDate = getTomorrowDateString();
  }
  onOpen() {
    var _a;
    this.setTitle("Defer until");
    new import_obsidian.Setting(this.contentEl).setName(this.noteTitle).setDesc("Pending tasks from this note stay hidden until this date.").addText((component) => {
      component.inputEl.type = "date";
      component.inputEl.min = this.minimumDate;
      component.setValue(this.getInitialDateValue());
      this.dateInputEl = component.inputEl;
      component.inputEl.addEventListener("keydown", (event) => {
        if (event.key !== "Enter") {
          return;
        }
        event.preventDefault();
        void this.submit();
      });
    });
    new import_obsidian.Setting(this.contentEl).addButton((button) => {
      button.setButtonText("Cancel").onClick(() => {
        this.close();
      });
    }).addButton((button) => {
      button.setButtonText("Save").setCta().onClick(() => {
        void this.submit();
      });
    });
    (_a = this.dateInputEl) == null ? void 0 : _a.focus();
    window.setTimeout(() => {
      var _a2;
      const dateInputEl = this.dateInputEl;
      try {
        (_a2 = dateInputEl == null ? void 0 : dateInputEl.showPicker) == null ? void 0 : _a2.call(dateInputEl);
      } catch (e) {
      }
    }, 0);
  }
  getInitialDateValue() {
    if (this.currentDeferredUntil && this.currentDeferredUntil >= this.minimumDate) {
      return this.currentDeferredUntil;
    }
    return this.minimumDate;
  }
  async submit() {
    var _a, _b;
    const deferredUntil = (_b = (_a = this.dateInputEl) == null ? void 0 : _a.value) != null ? _b : "";
    if (!isFutureDate(deferredUntil)) {
      new import_obsidian.Notice("Choose a future date.");
      return;
    }
    await this.onSubmitDate(deferredUntil);
    this.close();
  }
};
function buildRenderedDocument(snapshot, metadataCache, getBacklinkFiles) {
  var _a;
  const sections = [];
  const renderedGroups = [];
  const renderedTasks = [];
  const today = getTodayDateString();
  for (const group of snapshot.groups) {
    if (snapshot.filter === "pending" && isDeferred(group.deferredUntil, today)) {
      continue;
    }
    const visibleTasks = group.tasks.filter((task) => matchesFilter(task, snapshot.filter));
    if (visibleTasks.length === 0) {
      continue;
    }
    const linkText = escapeWikiLinkText(metadataCache.fileToLinktext(group.file, "/", true));
    const noteTitle = escapeWikiLinkText(group.noteTitle);
    sections.push(`## [[${linkText}|${noteTitle}]]`);
    renderedGroups.push(group);
    if (snapshot.filter === "all" && group.deferredUntil) {
      sections.push(buildDeferredUntilLine(group.deferredUntil));
    }
    if (snapshot.showConnections) {
      const backlinks = getBacklinkFiles(group.file);
      if (backlinks.length > 0) {
        sections.push(buildConnectionsLine(backlinks, metadataCache));
      }
    }
    for (const task of visibleTasks) {
      sections.push(task.renderedLine);
      renderedTasks.push(task);
    }
    sections.push("");
  }
  if (sections.length === 0) {
    const emptyMessage = (_a = snapshot.error) != null ? _a : snapshot.filter === "all" ? "No tasks." : `No ${filterDescription(snapshot.filter)} tasks.`;
    return {
      markdown: emptyMessage,
      renderedGroups,
      renderedTasks
    };
  }
  return {
    markdown: sections.join("\n").trim(),
    renderedGroups,
    renderedTasks
  };
}
function buildDeferredUntilLine(deferredUntil) {
  return `<span class="vault-tasks-view__deferred-label">Deferred until:</span> ${deferredUntil}`;
}
function buildConnectionsLine(backlinks, metadataCache) {
  const renderedLinks = backlinks.map((backlinkFile) => {
    const linkText = escapeWikiLinkText(metadataCache.fileToLinktext(backlinkFile, "/", true));
    return `[[${linkText}]]`;
  });
  return `<span class="vault-tasks-view__connections-label">Related to:</span> ${renderedLinks.join(", ")}`;
}
function buildTaskItem(file, taskItem, lines) {
  const line = taskItem.position.start.line;
  const rawLine = lines[line];
  if (rawLine === void 0) {
    return null;
  }
  const text = extractTaskText(rawLine);
  if (text === null) {
    return null;
  }
  return {
    completed: taskItem.task !== " ",
    file,
    key: `${file.path}:${line}`,
    line,
    rawLine,
    renderedLine: rawLine.trimStart(),
    text
  };
}
function collectEditorLines(editor) {
  const lines = [];
  for (let index = 0; index < editor.lineCount(); index += 1) {
    lines.push(editor.getLine(index));
  }
  return lines;
}
function escapeWikiLinkText(text) {
  return text.replace(/([\\[\]|])/g, "\\$1");
}
function extractTaskText(rawLine) {
  const match = rawLine.match(TASK_TEXT_PATTERN);
  return match ? match[1] : null;
}
function extractDeferredUntil(content) {
  return normalizeDeferredUntil(extractFrontmatterValue(content, DEFERRED_UNTIL_KEY));
}
function extractHiddenFromTaskList(content) {
  var _a;
  return (_a = normalizeFrontmatterBoolean(extractFrontmatterValue(content, HIDDEN_FROM_TASKS_KEY))) != null ? _a : false;
}
function filterLabel(filter) {
  switch (filter) {
    case "pending":
      return "Pending";
    case "completed":
      return "Completed";
    default:
      return "All";
  }
}
function filterIcon(filter) {
  switch (filter) {
    case "pending":
      return "circle";
    case "completed":
      return "check";
    default:
      return "list";
  }
}
function filterDescription(filter) {
  switch (filter) {
    case "pending":
      return "pending";
    case "completed":
      return "completed";
    default:
      return "all";
  }
}
function getTodayDateString() {
  return formatDate(/* @__PURE__ */ new Date());
}
function getTomorrowDateString() {
  const tomorrow = /* @__PURE__ */ new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  return formatDate(tomorrow);
}
function isDeferred(deferredUntil, today) {
  return deferredUntil !== null && deferredUntil > today;
}
function isFutureDate(date) {
  return DATE_PATTERN.test(date) && date >= getTomorrowDateString();
}
function isHiddenFromTaskListFrontmatter(frontmatter) {
  var _a;
  if (!frontmatter) {
    return false;
  }
  return (_a = normalizeFrontmatterBoolean(frontmatter[HIDDEN_FROM_TASKS_KEY])) != null ? _a : false;
}
function findTaskLine(lines, task) {
  const currentLine = lines[task.line];
  if (currentLine !== void 0) {
    const sameLine = currentLine === task.rawLine || extractTaskText(currentLine) === task.text;
    if (sameLine) {
      return task.line;
    }
  }
  const rawLineMatches = lines.map((line, index) => ({ index, line })).filter(({ line }) => line === task.rawLine);
  if (rawLineMatches.length === 1) {
    return rawLineMatches[0].index;
  }
  const textMatches = lines.map((line, index) => ({ index, text: extractTaskText(line) })).filter(({ text }) => text === task.text);
  if (textMatches.length === 1) {
    return textMatches[0].index;
  }
  return null;
}
function getTaskListItems(cache) {
  if (!(cache == null ? void 0 : cache.listItems)) {
    return [];
  }
  return cache.listItems.filter((item) => item.task !== void 0);
}
function matchesFilter(task, filter) {
  switch (filter) {
    case "pending":
      return !task.completed;
    case "completed":
      return task.completed;
    default:
      return true;
  }
}
function setTaskCompletion(rawLine, completed) {
  const match = rawLine.match(TASK_LINE_PATTERN);
  if (!match) {
    return null;
  }
  return `${match[1]}${completed ? "x" : " "}${match[3]}`;
}
function updateAllTasksInEditor(editor, completed) {
  let updatedCount = 0;
  for (let index = 0; index < editor.lineCount(); index += 1) {
    const rawLine = editor.getLine(index);
    const nextLine = setTaskCompletion(rawLine, completed);
    if (nextLine === null || nextLine === rawLine) {
      continue;
    }
    editor.setLine(index, nextLine);
    updatedCount += 1;
  }
  return updatedCount;
}
function updateTaskInContent(content, task, completed) {
  const newline = content.includes("\r\n") ? "\r\n" : "\n";
  const lines = content.split(/\r?\n/);
  const targetLine = findTaskLine(lines, task);
  if (targetLine === null) {
    throw new Error("The task moved before it could be updated. Refresh and try again.");
  }
  const nextLine = setTaskCompletion(lines[targetLine], completed);
  if (nextLine === null) {
    throw new Error("The source line is no longer a standard Markdown task.");
  }
  lines[targetLine] = nextLine;
  return lines.join(newline);
}
function updateAllTasksInContent(content, completed) {
  const newline = content.includes("\r\n") ? "\r\n" : "\n";
  const lines = content.split(/\r?\n/);
  let updatedCount = 0;
  for (let index = 0; index < lines.length; index += 1) {
    const rawLine = lines[index];
    const nextLine = setTaskCompletion(rawLine, completed);
    if (nextLine === null || nextLine === rawLine) {
      continue;
    }
    lines[index] = nextLine;
    updatedCount += 1;
  }
  return {
    content: lines.join(newline),
    updatedCount
  };
}
var DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
function formatDate(date) {
  const year = String(date.getFullYear());
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function normalizeDeferredUntil(value) {
  const unquotedValue = unquoteFrontmatterValue(value);
  return DATE_PATTERN.test(unquotedValue) ? unquotedValue : null;
}
function extractFrontmatterValue(content, key) {
  const frontmatterMatch = content.match(FRONTMATTER_PATTERN);
  if (!frontmatterMatch) {
    return null;
  }
  const frontmatter = frontmatterMatch[1];
  const valueMatch = frontmatter.match(new RegExp(`^${key}:\\s*(.+?)\\s*$`, "m"));
  return valueMatch ? valueMatch[1] : null;
}
function normalizeFrontmatterBoolean(value) {
  if (typeof value === "boolean") {
    return value;
  }
  if (typeof value !== "string") {
    return null;
  }
  switch (unquoteFrontmatterValue(value).toLowerCase()) {
    case "true":
    case "yes":
    case "on":
      return true;
    case "false":
    case "no":
    case "off":
      return false;
    default:
      return null;
  }
}
function unquoteFrontmatterValue(value) {
  if (value === null) {
    return "";
  }
  const trimmedValue = value.trim();
  return trimmedValue.startsWith('"') && trimmedValue.endsWith('"') || trimmedValue.startsWith("'") && trimmedValue.endsWith("'") ? trimmedValue.slice(1, -1) : trimmedValue;
}
